version: 0.2


phases:
  install:
    runtime-versions:
      java: corretto11
      nodejs: 16
    commands:
    - echo installing maven...
    - apt-get update -y
    - apt-get install -y maven
    - npm install -g newman

  build:
    commands:
    - echo building the justiceleague-tracker
    - java -version
    - mvn install
    - echo run the application
    - java -jar -Dspring.profiles.active=dev /home/ec2-user/justiceleague-tracker-0.0.1-SNAPSHOT.jar > /dev/null 2> /dev/null < /dev/null &
    - echo Running postman tests
    - newman run JL_Collection.postman_collection.json -r junit
reports:
  JUnitReports: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '**/*'
    base-directory: 'newman' # Location of the reports

artifacts:
  files:
  - target/*.jar
  - scripts/*.sh
  - appspec.yml
  discard-paths: yes

cache:
  paths:
  - '/root/.m2/**/*'
